version: "3"
services:
  mysql:
    image: "mysql:5.7.24"
    container_name: "generator-typeorm-example"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "test"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_DATABASE: "users"
